### PR TITLE
added docs for Postgresql setup in FreeBSD jails

### PR DESCRIPTION
**Pull request by c0psrul3**

### CODE REVIEW

**Comment by t-zuehlsdorff** [comment]
Hello @c0psrul3,

first: thanks for the patch!

But i need some more information. Since i'm a strong PostgreSQL user i need to now, with which PostgreSQL version in mind you wrote the patch? At least 9.5 and 9.6 really work without this changes. For 9.4 i would double check this - but its very likely that your update is needed.

**Comment by c0psrul3** [comment]
thank you for noting this, I hadn't even looked.  It is Pg 9.3
And, you're right, I should upgrade.  However, it was installed along with the FreeBSD Package "gitlab-8.10.12"
Would you mind telling me which versions of Pg (9.5 / 9.6) can be used with Gitlab 8.12 / 8.13?  I think it doesn't matter.
I'll upgrade and come back with any further doc patches.  Thanks!

**Comment by t-zuehlsdorff** [comment]
Hello Mike,
yes, PG 9.3 is the current default PostgreSQL version. We are currently trying to set 9.4 as new default.
The documentation states that GitLab needs PG 9.1 or higher, so it doesn't really matter, if you use 9.5 or 9.6. I use both.

**Comment by c0psrul3** [comment]
thanks for the info.
take the patch for what it's worth, then  :)

**Pull request merged**
