### PR TITLE
8 6 docu

### PR DESCRIPTION
**Pull request by miks**

### CODE REVIEW

**Comment by miks** [comment]
Take this more as my installation sidenotes, not as pull request to change anything.

**Comment by t-zuehlsdorff** [comment]
Hello Miks,

i will close this pull request without the complete merge. But let me thank you again for your work. I toke the update of the PostgreSQL version and the missing sysrc into the installation guide. :) This really misses!

Greetings,
Torsten

**Comment by miks** [comment]
What about that `bundle install` step?
There was some gems missing, so, that was stopper for me. Do you need list of missing gems?

**Comment by t-zuehlsdorff** [comment]
The whole point of the port is to skip the bundle install step. Reasons reaching from dependencies to security-issues.
Every gem needed should be installed by the port. Which one misses for you? Did you change the configuration to need others?

**Comment by miks** [comment]
I did not change anything. And that's why I already added that list https://gist.github.com/miks/0820c3a74b07d622f24b4e865652184d.
Search for "Installing", all those gems are missing:

```
Installing rake 11.1.2
Installing chunky_png 1.3.5
Installing rotp 2.1.2
Installing enumerable-lazy 0.0.1
Installing escape_utils 1.1.1 with native extensions
Installing request_store 1.3.1
Installing systemu 2.6.5
Installing newrelic_rpm 3.15.1.316
Installing redis 3.3.0
Installing recaptcha 1.3.0
Installing select2-rails 3.5.10
Installing attr_encrypted 1.3.5
Installing autoprefixer-rails 6.3.6
Installing rqrcode 0.10.1
Installing sprockets 3.6.0
Installing mustermann19 0.4.3
Installing github-linguist 4.8.3
Installing gitlab-grit 2.8.1
Installing ruby_parser 3.8.1
Installing faraday_middleware 0.10.0
Installing twitter-text 1.13.4
Installing grape-entity 0.5.1
Installing fog-openstack 0.1.3
Installing grape 0.16.2
Installing font-awesome-rails 4.6.1.0
Installing devise 3.5.7
```

**Comment by miks** [comment]
In reality, I think it quite unrealistic to keep port in sync with actual gitlab releases as all gems with versions needed by gitlab need to be also in freebsd ports.
Are security is only concern why all of this is so complicated (gems in ports instead of standart practice with gems from rubygems and installing with bundler vendor mode)?

**Comment by t-zuehlsdorff** [comment]
If you compare your list of "installing" gems to the actual list of ports: they all were already installed. Since the versions of the gems provided by the ports are higher  than the pessimistic operator in Gemfile wants, the above list is installed. Without any need.

Why should it be unrealistic to keep ports in sync? It is already real. You can use it, quite now. It is already used by multiple persons and there are already full services based on this! If you keep an eye on the development it is even easier. The next GitLab version requires currently 2 new gems, which are already in the portstree.

And the port approach is much easier than the standard practice. Without the port you need to perform the source-installation which is about 30% longer and contains this much more steps (and problems).
Security is one key issue. Dependencies are another. There are many gems which need other installed software - but rubygems will not install them. You need to do this by yourself, while the port does this for you. Same for updates and management. You can have pkg or you can have pkg and rubygems and npm and etc. Just as a short overview why i created a port. Beside the point that there are only 2 working guides how to install GitLab and both just works for old GitLab versions, so you are unable to get a current GitLab running as novice.

If you say this is all so complicated please be more specific. What is more complicate than the standard procedure of source-installation? Maybe i can ease it even more?

**Comment by miks** [comment]
> If you compare your list of "installing" gems to the actual list of ports: they all were already installed. Since the versions of the gems provided by the ports are higher than the pessimistic operator in Gemfile wants, the above list is installed. Without any need.

This I got on clean jail, that I just made:
```
pkg install gitlab
cd /usr/local/www/gitlab
/usr/local/www/gitlab # rake -T
Could not find gem 'attr_encrypted (~> 1.3.4)' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
```
It looks like this is the only issue by now, after manually installing this 1.3.4 version for "attr_encrypted" there was no other errors. 
But, I guess thats because I still got "8.5.5." when installing. Looked upon freshports and 1.3.4 was listed.

> If you say this is all so complicated please be more specific. What is more complicate than the standard procedure of source-installation? Maybe i can ease it even more?

Its more complicated as someone need to maintain all those gems to ports. We have many application developed in Rails and we never had any problems with plain old "bundle install" either be it Linux or FreeBSD. But as long as its works, is not more complicated then.

> Beside the point that there are only 2 working guides how to install GitLab and both just works for old GitLab versions, so you are unable to get a current GitLab running as novice.

I'm running Gitlab on FreeBSD started by Gitlab early versions few years ago (I even contributed some code to Gitlab). So, I have no problems to get Gitlab running at all. I want to make Gitlab FreeBSD port installation more realistic, that's all.

**Comment by t-zuehlsdorff** [comment]
> But, I guess thats because I still got "8.5.5." when installing. Looked upon freshports and 1.3.4 was listed.

Indeed. This is because you use the quartly branch, which sadly was broken by this Gem. If you use the current one, everythink is fine.

> Its more complicated as someone need to maintain all those gems to ports. We have many application developed in Rails and we never had any problems with plain old "bundle install" either be it Linux or FreeBSD. But as long as its works, is not more complicated then.

Maintaining is already done and the bigger problem is that the gems are often far too new for GitLab so we need to check if GitLab really works with them. Also most of the updates could be automatic. And as i mentioned: there is no "plain old bundle install". There are dependencies, security issues and another interface to handle.

> I'm running Gitlab on FreeBSD started by Gitlab early versions few years ago (I even contributed some code to Gitlab). So, I have no problems to get Gitlab running at all. I want to make Gitlab FreeBSD port installation more realistic, that's all.

Than you need to describe what is unrealistic. Because it works and many step you need to do without the port are already done.

I really like to discuss the port and issues user run into. That is were we can learn from. But we need to be more accurate. Getting a broken GitLab 8.5.5 from quartly-branch is indeed bad, so we should adress a fix to it. What else?

**Comment by miks** [comment]
Ok, I will try to install latest gitlab from ports and post my notes (I hope there will be none).

**Comment by miks** [comment]
1) I think if doc give insight how to enable and start Redis, so it must to same for PostgreSQL (including how to start it first time by initializing database first)
2) There is no need for "Change the Redis socket path if you are not using the default Debian / Ubuntu configuration" line as in previous step there "how to" to change socket path.
3) git user home is still "/usr/local/git".
4) When running "rake gitlab:setup RAILS_ENV=production" I got warning:
```
 Warning
  You are running as user root, we hope you know what you are doing.
  Things may work/fail for the wrong reasons.
  For correct results you should run this as user git.
```
As every gitlab process must be run as git user, why doc is recommending to run this step as root?
5) in same "rake gitlab:setup RAILS_ENV=production" step I got:
```
gitlabhq_production already exists
-- enable_extension("plpgsql")
   -> 0.0085s
-- enable_extension("pg_trgm")
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedFile: ERROR:  could not open extension control file "/usr/local/share/postgresql/extension/pg_trgm.control": No such file or directory
```
I installed PostgreSQL 9.3 with pkg, are this extension is from some configurable option for PostgreSQL?

**Comment by t-zuehlsdorff** [comment]
Hello miks,

please excuse my long response time. My family is currently ill and taking care of them has the highest prio.

To your points:
1)  You convinced me - i added this!
2) Good catch, removed!
3) That is nothing the port can/should handle. This is defined by the ports-framework and must be changed there.
4) Because there are numerous problems when doing this as git-user. Init as root, but running as git is the current behavior.
5) This is new since GitLab 8.6. You need the postgresql93-contrib module serving this extension. This could not be configured in the port, but i added the contrib port to the installation doc!

Thanks for your report. If there is anymore, please just add here! :)

**Comment by miks** [comment]
No worry for response time.
About third point and home path. Does your working version works fine when git user home directory is /usr/local/git ?

**Comment by t-zuehlsdorff** [comment]
Since /usr/local/git is the default home-dir and i do not know any use (besides you ;)) having problems with this: yes. 
I'm running two installations with this path and all is fine.

**Pull request closed without merging**
