### PR TITLE
A couple of minor gotchas for 8.7

### PR DESCRIPTION
**Pull request by corv89**
This is on 10.2-RELEASE-p15

### CODE REVIEW

**Comment by t-zuehlsdorff** [comment]
Hello,

thanks for the catches. :) Today i brought a update on the road with brings the quarterly version of GitLab to its newest version and fix the rake-issue. If you remove the passage i will merge it.
Another option would be to rephrase it and mention that the newest GitLab version is just available on /latest/.
Greetings,
Torsten

**Comment by corv89** [comment]
I will go over it again now that the update is out.

By the way, thank you for your work on this port.

Kind regards,
Corvin

**Comment by corv89** [comment]
I've pushed my amendments. I've also noticed that the newest version available on quarterly 10.2 is still gitlab 8.5.

**Comment by t-zuehlsdorff** [comment]
Hello corv89,

thanks for your changes! I merged them all :)

Greetings,
Torsten

**Pull request merged**
